apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
  namespace: default
data:
  DB_NAME: "{{ .Values.db.name }}"
  DB_USER: "{{ .Values.db.user }}"
  DB_HOST: "{{ .Values.db.host }}"
  DB_PORT: "{{ .Values.db.port }}"

